version: "2.1"
services:
  allure:
    image: "frankescobar/allure-docker-service"
    environment:
      CHECK_RESULTS_EVERY_SECONDS: 1
      KEEP_HISTORY: 1
    ports:
      - "5050:5050"
    volumes:
      - "C:/QA_AUTOMATION/MFTV_Web_Desktop_Smoke_JUnit5_only/allure-results:/app/allure-results"
      - "C:/QA_AUTOMATION/MFTV_Web_Desktop_Smoke_JUnit5_only/allure-reports:/app/default-reports"
  allure-ui:
    image: "frankescobar/allure-docker-service-ui"
    environment:
      ALLURE_DOCKER_PUBLIC_API_URL: "http://192.168.1.139:5050"
      ALLURE_DOCKER_PUBLIC_API_URL_PREFIX: ""
    ports:
      - "5252:5252"
  selenoid:
    image: aerokube/selenoid:latest-release
    volumes:
        - "C:/QA_AUTOMATION/MFTV_Web_Desktop_Smoke_JUnit5_only/WebDriver/init/selenoid:/etc/selenoid"
        - "C:/QA_AUTOMATION/MFTV_Web_Desktop_Smoke_JUnit5_only/WebDriver/working/selenoid/video:/opt/selenoid/video"
        - "C:/QA_AUTOMATION/MFTV_Web_Desktop_Smoke_JUnit5_only/WebDriver/working/selenoid/logs:/opt/selenoid/logs"
        - "/var/run/docker.sock:/var/run/docker.sock"

    environment:
      - OVERRIDE_VIDEO_OUTPUT_DIR=work/selenoid/video
    command: [ "-conf", "/etc/selenoid/browsers.json", "-video-output-dir", "/opt/selenoid/video", "-log-output-dir", "/opt/selenoid/logs" ]
    ports:
      - 4444:4444
    network_mode: bridge
  selenoid-ui:
    image: aerokube/selenoid-ui:latest-release
    network_mode: bridge
    links:
        - selenoid
    ports:
        - 8082:8080
    command: ["--selenoid-uri", "http://selenoid:4444"]
  vnc:
    image: selenoid/vnc:chrome_96.0
    network_mode: bridge
  test_runner:
    build:
#     context: /builds/qa/MFTV_Web_Desktop_Smoke_JUnit5_only
      context: C:\QA_AUTOMATION\MFTV_Web_Desktop_Smoke_JUnit5_only
#     dockerfile: /builds/qa/MFTV_Web_Desktop_Smoke_JUnit5_only/WebDriver/Dockerfile
      dockerfile: C:\QA_AUTOMATION\MFTV_Web_Desktop_Smoke_JUnit5_only\WebDriver\Dockerfile
    image: tests_webdriver
    container_name: tests_run_webdriver
    network_mode: "host"


