version: "2.1"
services:
  allure:
    image: "frankescobar/allure-docker-service"
    environment:
      CHECK_RESULTS_EVERY_SECONDS: 1
      KEEP_HISTORY: 1
    ports:
      - "5050:5050"
    depends_on:
      - test_runner
    volumes:
      - C:/QA_AUTOMATION/yandexzenvideo/WebDriver/build/allure-results:/app/allure-results
      - C:/QA_AUTOMATION/yandexzenvideo/WebDriver/build/allure-reports:/app/default-reports

  allure-ui:
    image: "frankescobar/allure-docker-service-ui"
    environment:
      ALLURE_DOCKER_PUBLIC_API_URL: "http://192.168.1.139:5050"
      ALLURE_DOCKER_PUBLIC_API_URL_PREFIX: ""
    ports:
      - "5252:5252"
    depends_on:
      - test_runner


  test_runner:
    build:
     context: C:\QA_AUTOMATION\yandexzenvideo\WebDriver
     dockerfile: C:\QA_AUTOMATION\yandexzenvideo\WebDriver\Dockerfile
    image: tests_webdriver
    container_name: tests_run_webdriver
    network_mode: "host"


