image: maven:latest

cache:
  paths:
    - .m2/repository/
    - target/

test:
  stage: test
  script:
    - mvn clean test
tags:
  - qa

deploy:
  stage: deploy
  script:
    - mvn io.qameta.allure:allure-maven:report


