cache:
  paths:
    - .m2/repository/
    - target/

stages:
  - build
  - test
  - deploy

build:
  image: docker:latest
  stage: build
  script:
    - apk add --no-cache docker-compose
    - docker-compose up

test:
  image: maven:latest
  stage: test
  script:
    - mvn clean test

deploy:
  stage: deploy
  script:
    - mvn io.qameta.allure:allure-maven:report

