image:
  - docker
  - maven:latest

services:
  - docker:dind
build:
  script:
    - apk add --no-cache docker-compose
    - docker-compose up -d
cache:
  paths:
    - .m2/repository/
    - target/

test:
  stage: test
  script:
    - mvn clean test

deploy:
  stage: deploy
  script:
    - mvn io.qameta.allure:allure-maven:report

