image: maven:latest

cache:
  paths:
    - .m2/repository/
    - target/

test:
  stage: test
  script:
    - docker-compose build
    - mvn clean test

deploy:
  stage: deploy
  script:
    - mvn io.qameta.allure:allure-maven:report

