image:
 name: docker/compose:latest
 entrypoint: [""]
services:
  - name: docker:dind

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TCP_PORT: 2375
  DOCKER_TLS_CERTDIR: ""

stages:
 - testPW-job
testPW-job:
 stage: testPW-job

 script:
  - docker -v
  - docker-compose -v
  - cd /builds/qa/autosmoke_mftv_web_and_mobile_web/mWebPlaywright
  - docker-compose up
 tags:
  - qa
 allow_failure: true
