services:
  - docker:dind

stages:
  - testPW-job
  - testWD-job
  - allure-job
testPW-job:
  stage: testPW-job
  script:
    - ls -l
    - pwd
    - cd /builds/qa/MFTV_Web_Desktop_Smoke_JUnit5_only/WebPlaywright
    - ls -l

  tags:
    - qa
  allow_failure: true

testWD-job:
  stage: testWD-job
  script:
    - cd /mnt/c/QA_AUTOMATION/MFTV_Web_Desktop_Smoke_JUnit5_only/WebDriver
    - docker-compose up
  tags:
    - qa
  allow_failure: true

allure-job:
  stage: allure-job
  script:
    - mvn io.qameta.allure:allure-maven:report

