image: docker

services:
  - docker:dind

stages:
  - testPW-job
  - testWD-job
  - allure-job
testPW-job:
  stage: testPW-job
  tags:
    - qa
  allow_failure: true
  script:
    - cd MFTV_Web_Desktop_Smoke_JUnit5_only\WebPlaywright
    - docker compose up

testWD-job:
  stage: testWD-job
  tags:
    - qa
  allow_failure: true
  script:
    - cd MFTV_Web_Desktop_Smoke_JUnit5_only\WebDriver
    - docker compose up

allure-job:
  stage: allure-job
  script:
    - mvn io.qameta.allure:allure-maven:report