image:
 name: docker/compose:latest
 entrypoint: [""]
services:
  - name: docker:dind

variables:
  DOCKER_HOST: tcp://docker:2375
#  DOCKER_IMAGE: ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/docker:19.03.13-dind
  DOCKER_TCP_PORT: 2375
  DOCKER_TLS_CERTDIR: ""

stages:
 - testPW-job
testPW-job:
 stage: testPW-job

 before_script:
  - docker login -u $CI_DEPENDENCY_PROXY_USER -p $CI_DEPENDENCY_PROXY_PASSWORD $CI_DEPENDENCY_PROXY_SERVER
 script:
  - docker -v
  - docker-compose -v
  - cd /builds/qa/autosmoke_mftv_web_and_mobile_web/mWebPlaywright
  - docker-compose up
 tags:
  - qa
 allow_failure: true
