#  version: "3"
#  services:
#    chrome:
#      image: gitlab.megafon.tv:443/qa/dependency_proxy/containers/mikhailnt87/selenium_node_chrome:4.1.1-20220121
#      shm_size: 2gb
#      ports:
#        - "5900"
#        - "7900"
#      depends_on:
#        - selenium-hub
#      environment:
#        - SE_EVENT_BUS_HOST=selenium-hub
#        - SE_EVENT_BUS_PUBLISH_PORT=4442
#        - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
#
#    selenium-hub:
#      image: gitlab.megafon.tv:443/qa/dependency_proxy/containers/mikhailnt87/selenium_hub:4.1.1-20220121
#      container_name: selenium-hub
#      ports:
#        - "4442:4442"
#        - "4443:4443"
#        - "4444:4444"


#version: "3"
#services:
#  standalone-chrome:
#    image: selenium/standalone-chrome:4.1.1-20220121
#    shm_size: 2gb
#    ports:
#      - "4444:4444"
#      - "7901:7900"
#
#  standalone-chrome2:
#    image: selenium/standalone-chrome:4.1.1-20220121
#    shm_size: 2gb
#    ports:
#      - "4444:4444"
#      - "7902:7900"
#
#  standalone-chrome3:
#    image: selenium/standalone-chrome:4.1.1-20220121
#    shm_size: 2gb
#    ports:
#      - "4444:4444"
#      - "7903:7900"

version: "3"
services:
  chrome:
    image: selenium/node-chrome:4.1.1-20220121
    shm_size: 2gb
    ports:
      - "5901:5900"
      - "5902:5900"
      - "7901:7900"
      - "7902:7900"
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_SESSION_RETRY_INTERVAL=2

  selenium-hub:
    image: selenium/hub:4.1.1-20220121
    container_name: selenium-hub
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"


