version: "4"
services:
  HubService:
    image: selenium/hub:4.1.1-20211217
    container_name: selenium-hub
    ports:
      - "4445:4444"
      - "4442:4442"
      - "4443:4443"

  CromeService:
    image: selenium/node-chrome:4.1.1-20211217
    shm_size: 2gb
    ports:
    - "5900"
    - "7900"
    depends_on:
      - HubService
    environment:
      - SE_EVENT_BUS_HOST=seleniumHub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - NODE_MAX_INSTANCES=1
      - NODE_MAX_SESSION=1



