package TestSmokeWebPlaywright.S4_Section_menu.SS1_New_and_Best_adWeb.SSS4_Collections.SSSS2_Tails_сontents;

import base.TestBasePlaywright;

public class Test_05_NIL_TAILS_Packages_in_collection_PW_adWeb extends TestBasePlaywright {
}
