package TestSmokeWebPlaywright.S4_Section_menu.SS1_New_and_Best_adWeb.SSS4_Collections.SSSS3_Collection_browsing_history;

import base.TestBasePlaywright;

public class Test_03_NIL_BROWSING_HISTORY_Edit_PW_adWeb extends TestBasePlaywright {
}
